language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: develpeliculasurjc
  on:
    all_branch: true
  api_key:
    secure: sddHD1EpbH383eNNWdu4myii0srB3cgCSgil0vbemGlgfTdDuFdqmHGqlXZvWHVudXC8DbKVDJ3/9rebW3WbxYhKW528KzbIZPzzovglr1HPZk+/HgSuu3hZKv9tOZ7nSiHUnHoeGuVdb0WWhnq3LbKT2yQqqiNFIIpXty9Fm7f2lwM29oaFWGeC3PUdKRrHpVAw78xor9rTm85iA687Sj/dDsCcy63d9n6zlhRblqGDIC7E5BY8hZQRLHpsSqXXwsFVL5OYXkWNwwMAR9OQiEZP5PQWqQNkhNAQSHL0E6BPzO6Jka4KKAW6mGYWOr+52n34Fk6uZrDszp3BYExBkgl6Hyv6i760eC8Q3n6uMrFepKcda+ca7SFaBIhIC/aECJSujFUikyMGBqNgTjCul/2ZzdpfengYvdGmyE7gd+W9apVmMeA0isIL8VJ9ZjtIpWkNH9W2WK7vBr/4pgJ9IHtJzTz9IzcxZnUrAIO7aQ/Dva2ST1ZC6q3dJSfuKnCMer78xVlWMN+ydcReX7DOGQFOv2r+W8+RWVLA2ijhAgZIryCjaW4QFWxBMfz2Ah6LgGX+AwYx/7RpDx0AA1NKX8ucVFAMUvKNfHTnrtBhDtbhpFH/g4+NCyarwDt63DD2tYp53YtpDaiJEDol+OvaLYtyW+fg9wUQk8evN7iB+D8=

